# Define cache to speed up builds
cache:
  paths:
    - node_modules/
    - .next/cache/

# Define pipeline stages
stages:
  - lint
  - test
  - build

# Install dependencies (runs before each job)
before_script:
  - npm ci --prefer-offline --no-audit

# Checks linting using eslint and formatting using prettier
# Runs on all branches and commits
lint:
  stage: lint
  image: node:24
  before_script:
    - npm ci
  script:
    - npm run lint

# Runs tests - must pass before deployment
# Runs on all branches and commits
test:
  stage: test
  image: node:24
  before_script:
    - npm ci
  script:
    - npm run test

# Builds the Next.js application
# Runs on all branches and commits
build:
  stage: build
  image: node:24
  before_script:
    - npm ci
  script:
    - npm run build
