# Define cache to speed up builds
cache:
  paths:
    - node_modules/
    - .next/cache/

# Define pipeline stages
stages:
  - lint
  - build-and-deploy

# Install dependencies (runs before each job)
before_script:
  - npm ci --prefer-offline --no-audit

format-check:
  stage: lint
  image: node:20
  before_script:
    - npm ci
  script:
    - npm run format:check
  only:
    - main

lint:
  stage: lint
  image: node:20
  before_script:
    - npm ci
  script:
    - npm run lint
  only:
    - main

# Build and deploy the Next.js application to GitLab Pages
pages:
  stage: build-and-deploy
  image: node:20
  script:
    - npm run build
    - ls -la out/
    - rm -rf public
    - mkdir -p public
    - cp -r out/* public/
    - ls -la public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
